// <auto-generated />
namespace OnlineBanking.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Kunde_EroeffnungsDatum : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Kunde_EroeffnungsDatum));
        
        string IMigrationMetadata.Id
        {
            get { return "202006100655587_Kunde_EroeffnungsDatum"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
